language: bash
sudo: required

os:
  - linux

env:
  global:
    - ECLIPSE_VERSION=2018-09
    - ECLIPSE_FILE=eclipse-java-${ECLIPSE_VERSION}-linux-gtk-x86_64.tar.gz

before_install:
  - sudo apt-get update
  - sudo apt-get install -y debhelper devscripts libsecret-1.0

install:
  - dpkg-buildpackage -uc -us
  - sudo dpkg -i ../eclipse-package*.deb

script:
  - wget ftp.halifax.rwth-aachen.de/eclipse//technology/epp/downloads/release/${ECLIPSE_VERSION}/R/${ECLIPSE_FILE}
  - make-eclipsepkg ${ECLIPSE_FILE}

notifications:
  email:
    on_success: change
    on_failure: change
